name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y linux-modules-extra-$(uname -r) can-utils iproute2

    - name: Add kernel module vcan
      run: |
        sudo modprobe vcan
        # sudo ip link add dev vcan0 type vcan
        # sudo ip link set up vcan0
        # ip link show vcan0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24

    - name: Build
      run: make build

    - name: Run tests
      # sudo is needed for can package tests
      run: sudo go test ./...

    - name: Format
      run: |
        DIFF="$(gofmt -d .)"
        if [[ -n $DIFF ]]; then
          echo "$DIFF"
          echo "please run gofmt"
          exit 1
        fi

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.60
